version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer:
    image: rabbitmq-consumer:latest
    hostname: consumer
    container_name: consumer
    restart: always
    depends_on:
      - rabbitmq


  producer:
    image: rabbitmq-producer:latest
    hostname: producer
    container_name: producer
    restart: always
    depends_on:
      - rabbitmq




