apiVersion: v1
kind: Secret
metadata:
  name:
    rabbitmq-secrets
type: Opaque
data:
    RABBITMQ_DEFAULT_USER: dXNlcg==
    RABBITMQ_DEFAULT_PASS: N1h4bU1ya0dSM0NXM2k5dg==
    RABBITMQ_DEFAULT_PORT: 5672
    RABBITMQ_DEFAULT_MESSAGE: 'CICD-Test-With-Environments'
    RABBITMQ_DEFAULT_SERVICE: 'rabbitmq-helm'