{{- if and .Values.secret (hasKey .Values.secret "enabled") (eq .Values.secret.enabled true) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}