apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-app
  template:
    metadata:
      labels:
        app: rabbitmq-app
    spec:
      containers:
      - name: rabbitmq-app
        image: rabbitmq:3-management
        ports:
          - containerPort: 5672
            name: rabbitmq
          - containerPort: 15672
            name: rabbitmq-web
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_DEFAULT_PASS

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq-app
  ports:
    - port: 5672
      targetPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-web
spec:
  selector:
    app: rabbitmq-app
  ports:
    - port: 15672
      targetPort: 15672
