apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-app
  template:
    metadata:
      labels:
        app: rancher-app
    spec:
      serviceAccountName: rancher-sa
      containers:
      - name: rancher-app
        image: rancher/rancher:head
        securityContext:
          privileged: true
          runAsUser: 0

---

apiVersion: v1
kind: Service
metadata:
  name: rancher-service
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: rancher-app